/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package openp2p/cmd */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
#endif

#endif

/* Start of preamble from import "C" comments.  */


#line 6 "openp2p_ohos.go"

#include <stdint.h>

#line 1 "cgo-generated-wrapper"


/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif


// OpenP2PStart starts the same in-process core used by Android. It returns
// after scheduling the login worker; the native caller observes connection
// progress through OpenP2PGetStatus/OpenP2PGetLastError.
//
extern int32_t OpenP2PStart(char* baseDir, char* token, int64_t shareBandwidth, int64_t logLevel);

// OpenP2PStartWithNode accepts a platform device-name candidate. The core uses
// it only when config.json has no non-empty network.Node value.
//
extern int32_t OpenP2PStartWithNode(char* baseDir, char* token, char* node, int64_t shareBandwidth, int64_t logLevel);

// OpenP2PStop stops the in-process core without terminating the host ability.
//
extern void OpenP2PStop();

// OpenP2PGetStatus returns the asynchronous core state:
// 0=stopped, 1=starting, 2=running, 3=failed.
//
extern int32_t OpenP2PGetStatus();

// OpenP2PIsRunning reports whether the core instance is alive. Network
// reachability, login state, SD-WAN assignment and TUN state are intentionally
// excluded so a temporary outage or port-forward-only mode is not restarted.
//
extern int32_t OpenP2PIsRunning();

// OpenP2PGetLastError copies the last asynchronous startup error into data.
//
extern int32_t OpenP2PGetLastError(char* data, int32_t capacity);

// OpenP2PGetSDWANConfig fills data with the JSON VPN configuration generated
// by the core. It blocks until the server sends a new configuration.
//
extern int32_t OpenP2PGetSDWANConfig(unsigned char* data, int32_t capacity);

// OpenP2PGetNodeName fills data with the local OpenP2P node name.
//
extern int32_t OpenP2PGetNodeName(char* data, int32_t capacity);

// OpenP2PGetHealth copies the current core/control/TUN packet health as JSON.
//
extern int32_t OpenP2PGetHealth(char* data, int32_t capacity);

// OpenP2PReadTun injects a packet read from the OHOS VPN fd.
//
extern void OpenP2PReadTun(unsigned char* data, int32_t length);

// OpenP2PWriteTun copies the next packet emitted by the core into data.
//
extern int32_t OpenP2PWriteTun(unsigned char* data, int32_t capacity, int32_t timeoutMs);

#ifdef __cplusplus
}
#endif
